GENRE_COUNT = 4
LIM_TRACKS = 50
COLUMNS = ['ID', 'TRACK_NAME', 'ARTISTS', 'RELEASE_YEAR', 'RELEASE_DECADE', 'DANCEABILITY', 'ENERGY','KEY', 'LOUDNESS', 'MODE', 'SPEECHINESS', 'ACOUSTICNESS', 'INSTRUMENTALNESS', 'LIVENESS', 'VALENCE', 'TEMPO', 'GENRE', 'LYRICS']